import type { NormalizedQuickAlertOptions } from './type';

export const DEFAULT_QUICK_ALERT_OPTIONS: Omit<NormalizedQuickAlertOptions, 'id'> = {
  title: '',
  subtitle: '',
  message: '',
  footer: '',
  type: 'success',
  timeout: 4000,
  toast: false,
  position: 'center',
  transition: 'slide',
  theme: 'default',
  buttons: null,
  showIcon: true,
  showDenyButton: false,
  showCloseButton: false,
  showProgressBar: true,
  showConfirmButton: false,
  showCancelButton: false,
  confirmButtonText: 'Confirm',
  okButtonText: 'OK',
  cancelButtonText: 'Cancel',
  denyButtonText: 'Deny',
  ariaLabel: '',
  confirmAriaLabel: '',
  denyAriaLabel: '',
  cancelAriaLabel: '',
  okAriaLabel: '',
  closeAriaLabel: '',
  confirmButtonClass: '',
  denyButtonClass: '',
  cancelButtonClass: '',
  okButtonClass: '',
  closeButtonClass: '',
  buttonVariant: 'solid',
  confirmButtonVariant: 'solid',
  denyButtonVariant: 'solid',
  cancelButtonVariant: 'solid',
  okButtonVariant: 'solid',
  pauseOnHover: true,
  pauseOnFocus: true,
  customClass: ''
};
